export { default as tissotLogo } from "././tissotLogo.jpg";
export { default as longinesLogo } from "././longines.jpg";
export { default as rolexLogo } from "././rolexLogo.jpg";
export { default as fredriqueLogo } from "././fredrique.svg";
// export { default as mauricoLogo } from "./maurico.png";
export { default as caisoLogo } from "././caisoLogo.jpg";
export { default as armandLogo } from "././armandLogo.png";
// export { default as hamiltonLogo } from "./hamilton.png";
export { default as westLogo } from "././west.png";
// export { default as bernhardLogo } from "./bernhard.webp";
// export { default as tagHeuerLogo } from "./tagHeuer";
// export { default as armaniLogo } from "./Armani.png";
// export { default as calvinLogo } from "./calvinLogo.webp";
// export { default as raymondLogo } from "./raymond.webp";
// export { default as ferragamoLogo } from "./FerragamoLogo.png";
// export { default as orientLogo } from "./orientLogo.png";
// export { default as seikoLogo } from "./seikoLogo.png";
// export { default as citizen } from "./citizenLogo.png";
// export { default as ingersoll } from "./ingersollLogo";
